# Generated by Django 5.1.7 on 2025-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_rename_number_of_hours_subject_laboratory_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
