# Generated by Django 5.1.7 on 2025-05-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_grade_year_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
