# Generated by Django 5.1.7 on 2025-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('Currently Taking', 'Currently Taking'), ('Drop', 'Drop'), ('Done', 'Done')], default='Currently Taking', max_length=20),
        ),
    ]
